# Generated by Django 5.2 on 2025-04-08 03:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TermoJuridico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termo_buscado', models.TextField()),
                ('traducao', models.TextField()),
                ('lei_relacionada', models.CharField(max_length=100)),
                ('tags', models.CharField(max_length=50)),
                ('data_busca', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buscas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico de Busca',
                'verbose_name_plural': 'Históricos de Busca',
            },
        ),
    ]
